//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargaIndividual
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectoriosCreditos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DirectoriosCreditos()
        {
            this.Logs = new HashSet<Logs>();
        }
    
        public int DirectorioCreditoId { get; set; }
        public string Autor { get; set; }
        public int CreditoId { get; set; }
        public string Archivo { get; set; }
        public Nullable<long> Tamanio { get; set; }
        public string Ruta { get; set; }
        public bool Procesado { get; set; }
        public Nullable<System.DateTime> FechaProcesado { get; set; }
        public bool Excepcion { get; set; }
        public string MotivoExcepcion { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logs> Logs { get; set; }
    }
}
