//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargaIndividual
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoPagos
    {
        public int HistoricoPagoId { get; set; }
        public int NumeroCredito { get; set; }
        public int Cuota { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public decimal Cargos { get; set; }
        public decimal Principal { get; set; }
        public decimal InteresVigente { get; set; }
        public decimal InteresVencido { get; set; }
        public decimal InteresOrdinario { get; set; }
        public decimal Cpa { get; set; }
        public decimal Moratorios { get; set; }
        public decimal Iva { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
    }
}
