//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargaIndividual
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JMValidacionesDBContext : DbContext
    {
        public JMValidacionesDBContext()
            : base("name=JMValidacionesDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DirectoriosCreditos> DirectoriosCreditos { get; set; }
        public virtual DbSet<HistoricoPagos> HistoricoPagos { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Movimientos> Movimientos { get; set; }
        public virtual DbSet<TablasAmortizacion> TablasAmortizacion { get; set; }
    }
}
