//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargaIndividual
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int LogId { get; set; }
        public int DirectorioCreditoId { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> NumeroLinea { get; set; }
    
        public virtual DirectoriosCreditos DirectoriosCreditos { get; set; }
    }
}
