//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargaIndividual
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablasAmortizacion
    {
        public int TablaAmortizacionId { get; set; }
        public int NumeroCredito { get; set; }
        public int NumeroPago { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Capital { get; set; }
        public decimal PagoCapital { get; set; }
        public decimal PagoInteresesMoratorios { get; set; }
        public decimal PagoInteresesOrdinarios { get; set; }
        public decimal PagoIvaIntereses { get; set; }
        public decimal PagoMensualTotal { get; set; }
        public decimal PagoFijoMensual { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
    }
}
